steps:
  # Checkout repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/SitiMonalisa/artikel-agro.git', '.']
    dir: '/workspace'

#   # Build container image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/IMAGE_NAME', '.']
#     dir: '/workspace'

#   # Push container image to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/IMAGE_NAME']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'artikel-api'
      - '--image'
      - 'gcr.io/$capstonec23-ps118/IMAGE_NAME'
      - '--region'
      - 'REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    env:
      - 'REGION=us-central1'  # Ganti dengan wilayah (region) yang diinginkan
      - 'SERVICE_NAME=service-name'  # Ganti dengan nama layanan yang Anda inginkan
      - 'IMAGE_NAME=image-name'  # Ganti dengan nama gambar Docker yang ingin Anda gunakan

